# **Módulo 2. Plataformas de Aplicación sobre Python**
---

In [4]:
import numpy as np
import pandas as pd

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## **Subtema 1.1 Trabajando con números aleatorios**

**Arreglo de una dimensión con valores aleatorios**

In [ ]:
rg = np.random.default_rng() 
aleatorio = rg.random(7)
print("Arreglo de números aleatorios: \n", aleatorio)

Arreglo de números aleatorios: 
 [0.14366912 0.65079564 0.14972484 0.60042327 0.12755753 0.41492034
 0.37317427]


**Matriz de Números flotantes aleatorios**

In [ ]:
rg = np.random.default_rng() 
aleatorio = rg.random((4, 5))
print("Matriz de números flotantes aleatorios: \n", aleatorio)

Matriz de números flotantes aleatorios: 
 [[0.95134777 0.21084048 0.85002406 0.63715107 0.72628591]
 [0.58323515 0.98727042 0.34596969 0.53157073 0.70722055]
 [0.08276286 0.99042356 0.13955588 0.46819452 0.04427735]
 [0.99498483 0.50013596 0.72741592 0.60099343 0.90882761]]


**Minireto 1**

En algunas ocasiones es importante trabajar con números aleatorios no flotantes. Realiza un pequeño script con Python y NumPy para crear un arreglo de 10 elementos enteros. Te recomiendo que acudas a la documentación de la función integers del módulo random de la plataforma NumPy.

**Minireto 2**

Ahora que sabes trabajar con números enteros aleatorios, crea una matriz de 6 filas por 4 columnas con todos sus valores aleatorios entre 0 y 100.

## **Subtema 1.2 Operaciones Matemáticas**

**Resta de arreglos**

In [ ]:
a = np.array( [10, 20, 30, 40, 50] )
b = np.array( [1, 2, 3, 4, 5] )
resta = a - b
print("Resultado de la resta de arreglos: \n", resta)

Resultado de la resta de arreglos: 
 [ 9 18 27 36 45]


**Suma de Matrices**

In [ ]:
rg = np.random.default_rng() 
MatA = rg.integers(20, size=(3, 3))
MatB = rg.integers(5, size=(3, 3))
sumaMat = MatA + MatB
print("MatA: \n", MatA)
print("MatB: \n", MatB)
print("Suma de MatA + MatB: \n", sumaMat)

MatA: 
 [[14 19 13]
 [15  3  8]
 [12 11  2]]
MatB: 
 [[1 1 4]
 [0 3 4]
 [4 4 2]]
Suma de MatA + MatB: 
 [[15 20 17]
 [15  6 12]
 [16 15  4]]


**Arreglo base para las siguientes operaciones**

In [ ]:
arreglo = np.arange(6)
print("Arreglo: ", arreglo)

Arreglo:  [0 1 2 3 4 5]


**Elevar los valores del arreglo a una potencia dada, por ejemplo al cuadrado**

In [ ]:
cuadrados = arreglo**2
print("Valores del arreglo al cuadrado: ", cuadrados)

Valores del arreglo al cuadrado:  [ 0  1  4  9 16 25]


**Multiplicando el arreglo por un escalar**

In [ ]:
arrescalar = arreglo * 5
print("Valores del arreglo por un escalar 5: ", arrescalar)

Valores del arreglo por un escalar 5:  [ 0  5 10 15 20 25]


**Obteniendo las raices cuadradas de cada uno de los elementos del arreglo**

In [ ]:
raices = np.sqrt(arreglo)
print("Raices cuadradas calculadas: ", raices)

Raices cuadradas calculadas:  [0.         1.         1.41421356 1.73205081 2.         2.23606798]


**Multiplicación de Matrices**

In [ ]:
rg = np.random.default_rng() 
MatA = rg.integers(20, size=(4, 3))
MatB = rg.integers(5, size=(3, 2))
multiplicacionMat = MatA @ MatB
print("MatA: \n", MatA)
print("MatB: \n", MatB)
print("Multiplicación de MatA * MatB: \n", multiplicacionMat)

MatA: 
 [[ 0 13 12]
 [11 16 15]
 [ 4  3 13]
 [ 6  7 14]]
MatB: 
 [[4 2]
 [3 0]
 [3 4]]
Multiplicación de MatA * MatB: 
 [[ 75  48]
 [137  82]
 [ 64  60]
 [ 87  68]]


**Minireto 1**

Realiza un script en Python que pida al usuario los tamaños de una matriz y sus valores y calcule el determinante de dicha matriz.

**Minireto 2**

Realiza un script en Python para resolver el siguiente problema: En una línea de manufactura se fabrican dos tipos de focos: transparentes (T) y opacos (O). De cada tipo se hacen cuatro modelos M1, M2, M3 y M4. Se debe pedir al operador del programa que introduzca la cantidad de focos que se realizaron de cada tipo y modelo. Considerando que el porcentaje de focos defectuosos del 2% para el modelo 1, el 5% para el modelo 2, el 8% para el modelo 3 y 10% para el modelo 4, calcule lo siguiente:
a)	La cantidad de focos transparentes en buen estado que se fabrican
b)	La cantidad de focos opacos defectuosos que se fabrican
c)	Cuál es el tipo y modelo de foco que más se produce en mal estado

## **Subtema 1.3 Inversa y Transpuesta**

**Matriz Transpuesta**

In [ ]:
rg = np.random.default_rng() 
MatA = rg.integers(30, size=(4, 3))
transpuesta = np.transpose(MatA)
print("MatA: \n", MatA)
print("Matriz Transpuesta: \n", transpuesta)

MatA: 
 [[ 5  2 10]
 [ 9 23 18]
 [14 19 18]
 [14 27 14]]
Matriz Transpuesta: 
 [[ 5  9 14 14]
 [ 2 23 19 27]
 [10 18 18 14]]


**Matriz inversa**

In [ ]:
matA = np.array([[1,2],[3,4]]) 
inversa = np.linalg.inv(matA) 
print ("Matriz A: \n", matA) 
print ("Matriz inversa de A: \n", inversa)

Matriz A: 
 [[1 2]
 [3 4]]
Matriz inversa de A: 
 [[-2.   1. ]
 [ 1.5 -0.5]]


**Minireto 1**

Realiza un script de Python para pedirle al usuario una matriz de NxM y calcular:

a.	Su matriz transpuesta

b.	Su matriz inversa y comprobar la relación de identidad 
     A x B = B x A = I

## **Subtema 2.1 Seleccionando subconjuntos de una tabla**

**Recuperando la estatura (height) de todos los personajes de Star Wars**

In [5]:
personajesSW = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/M2DCData/characters.csv")
alturasPersonajesSW = personajesSW["height"]
print('Tamaño del resultado: ', alturasPersonajesSW.shape)
alturasPersonajesSW.head()

Tamaño del resultado:  (87,)


0    172
1    167
2     96
3    202
4    150
Name: height, dtype: int64

**Seleccionando dos columnas (altura y especie)**

In [6]:
personajesSW = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/M2DCData/characters.csv")
datosPersonajesSW = personajesSW[["height", "species"]]
print('Tamaño del resultado: ', datosPersonajesSW.shape)
datosPersonajesSW.head()

Tamaño del resultado:  (87, 2)


height species
0     172   Human
1     167   Droid
2      96   Droid
3     202   Human
4     150   Human

**Seleccionando filas (todos los personajes  mas bajos de 100 cm)**

In [7]:
personajesSW = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/M2DCData/characters.csv")
personajesBajosSW = personajesSW[personajesSW["height"]<100]
print('Tamaño del resultado: ', personajesBajosSW.shape)
personajesBajosSW.head()

Tamaño del resultado:  (9, 11)


id                   name  height  ...  gender homeworld         species
2    3                  R2-D2      96  ...     NaN     Naboo           Droid
7    8                  R5-D4      97  ...     NaN  Tatooine           Droid
18  19                   Yoda      66  ...    male       NaN  Yoda's species
27  28           Arvel Crynyd      90  ...    male       NaN           Human
28  29  Wicket Systri Warrick      88  ...    male     Endor            Ewok

[5 rows x 11 columns]

**Seleccionando filas con condiciones compuestas (por ejemplo los personajes más altos a 170 cm y con peso mayor a 100 kg)**

In [8]:
personajesSW = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/M2DCData/characters.csv")
personajesAltosPesadosSW = personajesSW[(personajesSW["height"]>170) | (personajesSW["mass"]>100)]
print('Tamaño del resultado: ', personajesAltosPesadosSW.shape)
personajesAltosPesadosSW.head()

Tamaño del resultado:  (56, 11)


id               name  height   mass  ... birth_year gender homeworld species
0   1     Luke Skywalker     172   77.0  ...      19BBY   male  Tatooine   Human
3   4        Darth Vader     202  136.0  ...    41.9BBY   male  Tatooine   Human
5   6          Owen Lars     178  120.0  ...      52BBY   male  Tatooine   Human
8   9  Biggs Darklighter     183   84.0  ...      24BBY   male  Tatooine   Human
9  10     Obi-Wan Kenobi     182   77.0  ...      57BBY   male   Stewjon   Human

[5 rows x 11 columns]

**Seleccionando filas y columnas, utilizando loc y condicionales (por ejemplo, recuperar solo el nombre del personaje que mide mas de 170 cm)**

In [9]:
personajesSW = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/M2DCData/characters.csv")
personajesAltosSW = personajesSW.loc[personajesSW["height"]>170, "name"]
print('Tamaño del resultado: ', personajesAltosSW.shape)
personajesAltosSW.head()

Tamaño del resultado:  (56,)


0       Luke Skywalker
3          Darth Vader
5            Owen Lars
8    Biggs Darklighter
9       Obi-Wan Kenobi
Name: name, dtype: object

**Seleccionando filas y columnas en base a su posición (por ejemplo recuperando los registros del 20 al 30 y las columnas de la 2 a la 6)**

In [10]:
personajesSW = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/M2DCData/characters.csv")
personajesAltosSW = personajesSW.iloc[19:29, 1:7]
print('Tamaño del resultado: ', personajesAltosSW.shape)
personajesAltosSW.head()

Tamaño del resultado:  (10, 6)


name  height   mass hair_color skin_color eye_color
19         Palpatine     170   75.0       grey       pale    yellow
20         Boba Fett     183   78.2      black       fair     brown
21             IG-88     200  140.0       none      metal       red
22             Bossk     190  113.0       none      green       red
23  Lando Calrissian     177   79.0      black       dark     brown

**Minireto 1**

Utiliza el mismo archivo de personajes de Star Wars y obtén lo siguiente:

a.	Todos los registros, pero solamente las columnas: name, homeworld y species.

b.	Obtén todos los personajes que tienen los ojos azules.

c.	Obtén todos los registros en las posiciones impares y todas las columnas de las posiciones pares.


## **Subtema 2.2 Creando columnas derivadas**

**Creando una columna derivada para representar la altura en metros**

In [11]:
personajesSW = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/M2DCData/characters.csv")
personajesSW["height_m"] = personajesSW["height"] / 100
personajesSW.head()

id            name  height   mass  ...  gender homeworld species height_m
0   1  Luke Skywalker     172   77.0  ...    male  Tatooine   Human     1.72
1   2           C-3PO     167   75.0  ...     NaN  Tatooine   Droid     1.67
2   3           R2-D2      96   32.0  ...     NaN     Naboo   Droid     0.96
3   4     Darth Vader     202  136.0  ...    male  Tatooine   Human     2.02
4   5     Leia Organa     150   49.0  ...  female  Alderaan   Human     1.50

[5 rows x 12 columns]

**Utilizando dos columnas del dataframe para crear una nueva columna derivada (por ejemplo el índice de masa corporal de los personajes)**

In [12]:
personajesSW = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/M2DCData/characters.csv")
personajesSW["imc"] = personajesSW["mass"] / (personajesSW["height"] / 100) ** 2 
personajesSW.head()

id            name  height   mass  ...  gender homeworld species        imc
0   1  Luke Skywalker     172   77.0  ...    male  Tatooine   Human  26.027582
1   2           C-3PO     167   75.0  ...     NaN  Tatooine   Droid  26.892323
2   3           R2-D2      96   32.0  ...     NaN     Naboo   Droid  34.722222
3   4     Darth Vader     202  136.0  ...    male  Tatooine   Human  33.330066
4   5     Leia Organa     150   49.0  ...  female  Alderaan   Human  21.777778

[5 rows x 12 columns]

**Minireto 1**

Utiliza el mismo archivo de personajes de Star Wars para:

•	Crear una columna nueva llamada grams que contenga el peso del personaje en gramos

•	Crear una columna nueva llamada vaccine que contenga el valor ‘Apply’ si hay que aplicar la vacuna y ‘No’ en caso de que no haya que aplicarla, la única regla es que se aplicará solamente a las mujeres.

•	¿Puede realizar el punto anterior introduciendo una función de NumPy que realice el trabajo equivalente?


## **Subtema 3.1 Calculando resúmenes con Pandas**

**Aplicando el cálculo del promedio a la columna height para obtener la altura promedio de los personajes de Star Wars**

In [13]:
personajesSW = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/M2DCData/characters.csv")
print("La altura promedio de los personajes de star wars es: ", personajesSW["height"].mean())

La altura promedio de los personajes de star wars es:  171.816091954023


**Aplicando el cálculo del promedio a dos columnas (height y mass) para obtener la altura y peso promedio de los personajes de Star Wars**

In [14]:
personajesSW = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/M2DCData/characters.csv")
personajesSW[["height", "mass"]].median()

height    178.0
mass       80.0
dtype: float64

**Aplicando diversos cálculos a varias columnas al mismo tiempo**

In [15]:
personajesSW = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/M2DCData/characters.csv")
personajesSW[["height", "mass"]].median()
personajesSW.agg(
        {
            "height": ["min", "max", "median", "skew"],
            "mass": ["min", "max", "median", "mean"],
        }
    )

height         mass
max     264.000000  1358.000000
mean           NaN    94.245977
median  178.000000    80.000000
min      45.000000    15.000000
skew     -1.218196          NaN

**Agrupando resultados (por ejemplo, obtener el promedio de peso de los personajes de Star Wars pero agrupandolos por su género)**

In [16]:
personajesSW = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/M2DCData/characters.csv")
personajesSW[["gender", "mass"]].groupby("gender").mean()

mass
gender                    
female           63.642105
hermaphrodite  1358.000000
male             85.374194
none            100.000000

**Contando el número de registros por categoría (por ejemplo por género)**

In [17]:
personajesSW = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/M2DCData/characters.csv")
personajesSW["gender"].value_counts()

male             62
female           19
none              2
hermaphrodite     1
Name: gender, dtype: int64